# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  garnet_config = debug
  audio_config = debug
  graphics_config = debug
  physics_config = debug
  networking_config = debug
endif
ifeq ($(config),release)
  garnet_config = release
  audio_config = release
  graphics_config = release
  physics_config = release
  networking_config = release
endif

PROJECTS := garnet audio graphics physics networking

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

garnet: audio graphics physics networking
ifneq (,$(garnet_config))
	@echo "==== Building garnet ($(garnet_config)) ===="
	@${MAKE} --no-print-directory -C . -f garnet.make config=$(garnet_config)
endif

audio:
ifneq (,$(audio_config))
	@echo "==== Building audio ($(audio_config)) ===="
	@${MAKE} --no-print-directory -C settings -f audio.make config=$(audio_config)
endif

graphics:
ifneq (,$(graphics_config))
	@echo "==== Building graphics ($(graphics_config)) ===="
	@${MAKE} --no-print-directory -C settings -f graphics.make config=$(graphics_config)
endif

physics:
ifneq (,$(physics_config))
	@echo "==== Building physics ($(physics_config)) ===="
	@${MAKE} --no-print-directory -C settings -f physics.make config=$(physics_config)
endif

networking:
ifneq (,$(networking_config))
	@echo "==== Building networking ($(networking_config)) ===="
	@${MAKE} --no-print-directory -C settings -f networking.make config=$(networking_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f garnet.make clean
	@${MAKE} --no-print-directory -C settings -f audio.make clean
	@${MAKE} --no-print-directory -C settings -f graphics.make clean
	@${MAKE} --no-print-directory -C settings -f physics.make clean
	@${MAKE} --no-print-directory -C settings -f networking.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   garnet"
	@echo "   audio"
	@echo "   graphics"
	@echo "   physics"
	@echo "   networking"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"